### ISSUE TITLE
Postman Assignments for QA and Manager 2: Use Postman for testing - GET, POST, PUT, DELETE 

### ISSUE THREAD

**Issue by writerity-toru-ugawa** [timeriver/trg_api#37]
### Epic

- #2 

Estimated required time: 20m - 40m/所要時間 20分～40分

### Purpose of this assignment/この課題の目的
Understanding how to use postman
Postmanの使い方を理解する

### How to proceed/進め方
Please make 1 ticket for submission. /課題提出用のチケット1枚発行してください。 
Ticket title and assignees /チケット内容は下記

**Title/タイトル:** 
Postman Assignments for QA and Manager 2: Use Postman for testing 

**Assignees/アサイニー:** 
yourself/自分

**Description(contents) / ディスクリプション（内容）：**
Screenshot of each request in postman and result 
各課題の、リクエスト内容と結果のスクリーンショット 

### Preparation / 準備
https://my-json-server.typicode.com/timeriver/trg_api
Above URL is to call API
上記がAPIコールのためのURLとなります。

You can see the data here too: 
データはこちらからも参照できます。
https://github.com/timeriver/trg_api/blob/main/db.json

### Assignment 1: Basic Request/基本的なリクエスト1 - GET
send an API Request to post and GET information on all posts. 
Please share a screenshot of the Request content (URL) and the Body content. 

postへAPI Requestを送信し、Postすべての情報をGETしてください。
Request内容（URL）と、Bodyの内容をスクリーンショットで共有してください。

Hint/ヒント：
endpoint is 
https://my-json-server.typicode.com/timeriver/trg_api/posts
GETのリクエスト先は　 
https://my-json-server.typicode.com/timeriver/trg_api/posts

### Assignment 2: Basic Request/基本的なリクエスト2 - GET

1. GET all posts of user id = 1. Please share the Request content (URL) and a screenshot of the Body content.
2. Answer what is the appropriate response to return from the GET method and why. 

Share the following screenshot and answer. 
- Request destination and request body content 
- Returned status (200, 201, ... etc.)
- Answer of (2)

1. User id=1のpostsをすべてGETしてください。
Request内容（URL）と、Bodyの内容をスクリーンショットで共有してください。
2. GETメソッドからリターンするレスポンスは何が適切か、それはなぜかを回答してください。
 
下記のスクリーンショットと回答を共有してください。
- リクエスト先とリクエストボディの内容
- 返ってきたステータス（200,201, ... など）
- (2)の回答

### Assignment 3: Basic Request/基本的なリクエスト3 - POST

1. Use the POST method to create a new post. (The content can be anything.) 
2. answer what is the appropriate response to return from the POST method and why. 

Share the following screenshot and answer. 
- Request destination and request body content 
- Returned status (200, 201, ... etc.)
- Answer of (2)

1. POSTメソッドを使い、新しいポストを作成してください。
（内容は何でもかまいません）
2. POSTメソッドからリターンするレスポンスは何が適切か、それはなぜかを回答してください。
 
下記のスクリーンショットと回答を共有してください。
- リクエスト先とリクエストボディの内容
- 返ってきたステータス（200,201, ... など）
- (2)の回答
- 
Hint/ヒント：
You can use Body > Row to post
Body > Row を利用してPOSTができます
<img width="318" alt="image" src="https://github.com/sacdev/trg_laravel/assets/144236668/6f2fcbb3-e23f-440d-b0e5-f4f531049472">

### Assignment 4: Basic Request/基本的なリクエスト4 - PUT

1. Use the PUT method to update the title and content of the post with comment id = 1. (The content can be anything)
2. Answer what is the appropriate response to return from the PUT method and why. 

Share the following screenshots and answer. 
- Request destination and request body content 
- returned status (200, 201, ... etc.)
- Answer of (2) 

1. PUTメソッドを使い、comment id = 1のポストのタイトルと内容を更新してください。
（内容は何でも構いません。）
2. PUTメソッドからリターンするレスポンスは何が適切か、それはなぜかを回答してください。

下記のスクリーンショットと回答を共有してください。
- リクエスト先とリクエストボディの内容
- 返ってきたステータス（200,201, ... など）
- (2)の回答

Hint/ヒント：
You can use Body > Row to post
Body > Row を利用してPOSTができます

### Assignment 5: Basic Request/基本的なリクエスト5 - DELETE

1. Use the DELETE method to delete post of post id = 2.
2. Answer what is the appropriate response to return from the DELETE method and why. 

Share the following screenshots. 
- Request destination and request body content 
- returned status (200, 201, ... etc.)
- Answer of (3) 

1. DELETEメソッドを使い、post id = 2のポストを削除してください。
2. DELETEメソッドからリターンするレスポンスは何が適切か、それはなぜかを回答してください。

下記のスクリーンショットを共有してください。
- リクエスト先とリクエストボディの内容
- 返ってきたステータス（200,201, ... など）
- (2)の回答

### Reference/参考
https://jsonplaceholder.typicode.com/guide/
https://blog.postman.com/what-are-http-status-codes/
https://restfulapi.net/http-methods/

**Comment by writerity-toru-ugawa** [comment]
@writerity-mami-asakura @writerity-mitsuru-kobayashi 
おつかれさまです！ご確認お願いします。

- [ ] **Assignment 1: Basic Request/基本的なリクエスト1 - GET**

![スクリーンショット 2024-07-08 092938](https://github.com/timeriver/trg_api/assets/167416036/6df18f0f-3e80-4b27-8184-db423bc0481f)


- [ ] **Assignment 2: Basic Request/基本的なリクエスト2 - GET**

Q1: GET all posts of user id = 1. Please share the Request content (URL) and a screenshot of the Body content.
![スクリーンショット 2024-07-08 142011](https://github.com/timeriver/trg_api/assets/167416036/4deff9bc-d535-4782-a2f0-546fdb112d40)

 Q2: Answer what is the appropriate response to return from the GET method and why?
-> As request is successful, appropriate response. status: 200 OK


- [ ] **Assignment 3: Basic Request/基本的なリクエスト3 - POST**

Q1: Use the POST method to create a new post. (The content can be anything.)
![スクリーンショット 2024-07-08 143336](https://github.com/timeriver/trg_api/assets/167416036/b41fd34e-fc6a-4934-a76b-93b058946895)
Q2: Answer what is the appropriate response to return from the POST method and why?
-> When a new data has been created, the 'send' would return status code '201' . The body section also returns with the newly created data

- [ ] **Assignment 4: Basic Request/基本的なリクエスト4 - PUT**
Q1: Use the PUT method to update the title and content of the post with comment id = 1. (The content can be anything)

![スクリーンショット 2024-07-08 144100](https://github.com/timeriver/trg_api/assets/167416036/13cca06a-2a78-46ba-aba5-968315602f9c)

Q2: Answer what is the appropriate response to return from the PUT method and why?
-> When the PUT request was run successfully, it returns the status code 200 OK. Also, the body section returns with the updated results


- [ ] **Assignment 5: Basic Request/基本的なリクエスト5 - DELETE**

Q1: Use the DELETE method to delete post of post id = 2.
![スクリーンショット 2024-07-08 144344](https://github.com/timeriver/trg_api/assets/167416036/e3cb5fbf-55df-47df-944d-44629180d108)

 Q2: Answer what is the appropriate response to return from the DELETE method and why?
-> Appropriate response to return from Delete method are: 202 OK, 204 Accepted or 204 No content. Also, the body content with empty content would be returned as record would have been deleted.

**Comment by writerity-mami-asakura** [comment]
@writerity-toru-ugawa 
見るのが遅くなりすみません！All OKです！！
チケットクローズいただいて大丈夫です。
