### ISSUE TITLE
Postman Assignments for QA and Manager 3: Use Postman for testing - Write Test Script 1

### ISSUE THREAD

**Issue by writerity-marina-funatsu** [timeriver/trg_api#41]
## Purpose of this assignment 
Understand how to write test script in Postman
Postmanでのテストスクリプトの書き方を理解する。

## Assignment 1 

Please write a test script to check if we can get product information from
下記のプロダクト情報を確認するテストスクリプトを作成する。
https://fakestoreapi.com/

#### Create GET request for getting product id = 10 / Product id =10のプロダクトを取得するGETリクエストを作成する
  https://fakestoreapi.com/products/

#### Write a test script 

**The things to check (What test script should check)/テストスクリプトに含めるべきこと** 
- 1. Returned Status code is 200 / レスポンスのステータスコードが200であること。
- 2. product id is 10 / 取得したProductのIDが10であること
- 3. product price is 109/取得したProductのPriceが109であること

### Reference 

Test Script for Postman 
https://learning.postman.com/docs/writing-scripts/test-scripts/

**Comment by writerity-marina-funatsu** [comment]
@writerity-mami-asakura 

お疲れ様です！お手すきの際レビューをお願いいたします。

![Image](https://github.com/user-attachments/assets/276d1715-754a-4a43-a0dd-e2a4e296b26b)

参考：https://qiita.com/Keiji_otsubo/items/69d196cf02dc7d3663b6


上記、ほぼ参考資料のコードコピペで完了してしまったため、constで定義せずに記述する方法を考えてみようと思い、色々試したところ一応合格が出ました。

![Image](https://github.com/user-attachments/assets/8e94d901-3128-492f-bda7-731405fc3d04)

こちらも間違っているところがあれば教えていただけますと幸いです。

**Comment by writerity-mami-asakura** [comment]
@writerity-marina-funatsu 
課題お疲れ様でした！合ってます！
