### ISSUE TITLE
Postman Assignments for QA and Manager 3: Use Postman for testing - Write Test Script 1

### ISSUE THREAD

**Issue by gamenic-aaryashree** [timeriver/trg_api#48]
Issue : #3 

## Purpose of this assignment 
Understand how to write test script in Postman
Postmanでのテストスクリプトの書き方を理解する。

## Assignment 1 

Please write a test script to check if we can get product information from
下記のプロダクト情報を確認するテストスクリプトを作成する。
https://fakestoreapi.com/

#### Create GET request for getting product id = 10 / Product id =10のプロダクトを取得するGETリクエストを作成する
  https://fakestoreapi.com/products/

#### Write a test script 

**The things to check (What test script should check)/テストスクリプトに含めるべきこと** 
- 1. Returned Status code is 200 / レスポンスのステータスコードが200であること。
- 2. product id is 10 / 取得したProductのIDが10であること
- 3. product price is 109/取得したProductのPriceが109であること

### Reference 

Test Script for Postman 
https://learning.postman.com/docs/writing-scripts/test-scripts/

**Comment by gamenic-aaryashree** [comment]
Hello , @gamenic-deepesh san , @gamenic-gaurav san, @writerity-mami-asakura san, @writerity-mitsuru-kobayashi san , @writerity-toru-ugawa san 

**For your review.**
- [x] 1. Returned Status code is 200
- [x] 2. Product id is 10
- [x] 3. Product price is 109
![image](https://github.com/user-attachments/assets/7a3409e8-6969-4337-8c0b-fcbba0f4e016)

**Comment by writerity-mami-asakura** [comment]
@gamenic-aaryashree 
All good! You can close this ticket ;)
