### ISSUE TITLE
Postman Assignments for QA and Manager 2: Use Postman for testing - GET, POST, PUT, DELETE

### ISSUE THREAD

**Issue by gamenic-prizma** [timeriver/trg_api#7]
### Assignment 1: Basic Request/基本的なリクエスト1 - GET
send an API Request to post and GET information on all posts. 
Please share a screenshot of the Request content (URL) and the Body content. 

postへAPI Requestを送信し、Postすべての情報をGETしてください。
Request内容（URL）と、Bodyの内容をスクリーンショットで共有してください。

Hint/ヒント：
endpoint is 
https://my-json-server.typicode.com/timeriver/trg_api/posts
GETのリクエスト先は　 
https://my-json-server.typicode.com/timeriver/trg_api/posts

### Assignment 2: Basic Request/基本的なリクエスト2 - GET

1. GET all posts of user id = 1. Please share the Request content (URL) and a screenshot of the Body content.
2. Answer what is the appropriate response to return from the GET method and why. 

Share the following screenshot and answer. 
- Request destination and request body content 
- Returned status (200, 201, ... etc.)
- Answer of (2)

1. User id=1のpostsをすべてGETしてください。
Request内容（URL）と、Bodyの内容をスクリーンショットで共有してください。
2. GETメソッドからリターンするレスポンスは何が適切か、それはなぜかを回答してください。
 
下記のスクリーンショットと回答を共有してください。
- リクエスト先とリクエストボディの内容
- 返ってきたステータス（200,201, ... など）
- (2)の回答

### Assignment 3: Basic Request/基本的なリクエスト3 - POST

1. Use the POST method to create a new post. (The content can be anything.) 
2. answer what is the appropriate response to return from the POST method and why. 

Share the following screenshot and answer. 
- Request destination and request body content 
- Returned status (200, 201, ... etc.)
- Answer of (2)

1. POSTメソッドを使い、新しいポストを作成してください。
（内容は何でもかまいません）
2. POSTメソッドからリターンするレスポンスは何が適切か、それはなぜかを回答してください。
 
下記のスクリーンショットと回答を共有してください。
- リクエスト先とリクエストボディの内容
- 返ってきたステータス（200,201, ... など）
- (2)の回答
- 
Hint/ヒント：
You can use Body > Row to post
Body > Row を利用してPOSTができます
<img width="318" alt="image" src="https://github.com/sacdev/trg_laravel/assets/144236668/6f2fcbb3-e23f-440d-b0e5-f4f531049472">

### Assignment 4: Basic Request/基本的なリクエスト4 - PUT

1. Use the PUT method to update the title and content of the post with comment id = 1. (The content can be anything)
2. Answer what is the appropriate response to return from the PUT method and why. 

Share the following screenshots and answer. 
- Request destination and request body content 
- returned status (200, 201, ... etc.)
- Answer of (2) 

1. PUTメソッドを使い、comment id = 1のポストのタイトルと内容を更新してください。
（内容は何でも構いません。）
2. PUTメソッドからリターンするレスポンスは何が適切か、それはなぜかを回答してください。

下記のスクリーンショットと回答を共有してください。
- リクエスト先とリクエストボディの内容
- 返ってきたステータス（200,201, ... など）
- (2)の回答

Hint/ヒント：
You can use Body > Row to post
Body > Row を利用してPOSTができます

### Assignment 5: Basic Request/基本的なリクエスト5 - DELETE

1. Use the DELETE method to delete post of post id = 2.
2. Answer what is the appropriate response to return from the DELETE method and why. 

Share the following screenshots. 
- Request destination and request body content 
- returned status (200, 201, ... etc.)
- Answer of (3) 

1. DELETEメソッドを使い、post id = 2のポストを削除してください。
2. DELETEメソッドからリターンするレスポンスは何が適切か、それはなぜかを回答してください。

下記のスクリーンショットを共有してください。
- リクエスト先とリクエストボディの内容
- 返ってきたステータス（200,201, ... など）
- (2)の回答

### Reference/参考
https://jsonplaceholder.typicode.com/guide/
https://blog.postman.com/what-are-http-status-codes/
https://restfulapi.net/http-methods/

**Comment by gamenic-prizma** [comment]
@writerity-mami-asakura @writerity-mitsuru-kobayashi 

### Assignment 1: Basic Request/基本的なリクエスト1 - GET

#### URL & Body
<img width="746" alt="get-1" src="https://github.com/timeriver/trg_api/assets/136424395/c1b7dc4a-54b4-4ca1-80ba-2358944fe904">


### Assignment 2: Basic Request/基本的なリクエスト2 - GET

1. GET all posts of user id = 1. Please share the Request content (URL) and a screenshot of the Body content.

#### URL & Body
<img width="719" alt="get-2" src="https://github.com/timeriver/trg_api/assets/136424395/092c3757-1f1a-40c7-9c4b-a3de153d6855">

2. What is the appropriate response to return from the GET method and why?
=> If the request is successful then returns status code 200 OK and also the server is returning the requested data.

### Assignment 3: Basic Request/基本的なリクエスト3 - POST

1. Use the POST method to create a new post. (The content can be anything.) 
<img width="635" alt="post" src="https://github.com/timeriver/trg_api/assets/136424395/8e0ab28c-9596-4176-a591-4cf3bdb00339">

2. Answer what is the appropriate response to return from the POST method and why?
=> The appropriate response to return from a POST method is '201 Created' which indicates that the request has been fulfilled and has resulted in the creation of a new resource.

### Assignment 4: Basic Request/基本的なリクエスト4 - PUT

1. Use the PUT method to update the title and content of the post with comment id = 1. (The content can be anything)
<img width="638" alt="put" src="https://github.com/timeriver/trg_api/assets/136424395/eb3cb331-9b78-4123-b148-70686785ac0e">

2. Answer what is the appropriate response to return from the PUT method and why?
=> Upon a successful PUT request, it responded with the widely used status code 200 OK, signifying the successful update of the resource.

### Assignment 5: Basic Request/基本的なリクエスト5 - DELETE

1. Use the DELETE method to delete post of post id = 2.
<img width="636" alt="delete" src="https://github.com/timeriver/trg_api/assets/136424395/d951475b-7387-411e-8228-9f1f8f52e1d5">

2. Answer what is the appropriate response to return from the DELETE method and why?
=>The appropriate response from the DELETE method is typically indicated by status code 204 (No Content), accompanied by an empty response body. Alternatively, the status code 200 OK can also be deemed acceptable.

**Comment by writerity-mami-asakura** [comment]
@gamenic-prizma 
Good work, you can close this ticket
